site_name: Intel ad-rss-lib
repo_url: https://github.com/intel/ad-rss-lib
docs_dir: doc
edit_uri: 'edit/master/doc/'
theme: readthedocs

nav:
- Home: index.md
- Release Notes and Disclaimer: RELEASE_NOTES_AND_DISCLAIMERS.md
- Background:
  - Overview: ad_rss/Overview.md
  - Design Discussions: ad_rss/HLD-KeyDesignDecisionsAndAlternatives.md
  - Unstructured Scenes: ad_rss/UnstructuredScenes.md
  - System Integration: ad_rss/HLD-ArchitectureOverview.md
  - Safety: ad_rss/HLD-Safety.md
  - Security: ad_rss/HLD-Security.md
  - Parameter Discussion: ad_rss/Appendix-ParameterDiscussion.md
  - Supported RSS Features: ad_rss/SupportedRssFeatures.md
- Map Integration:
  - Overview: ad_rss_map_integration/Main.md
  - Construction of the RSS Scenes: ad_rss_map_integration/ConstructRSSScenes.md
  - Handling of road boundaries: ad_rss_map_integration/HandleRoadBoundaries.md
- Building:
  - BUILDING.md
- Python Integration:
  - Core Library: ad_rss/ad_rss_python.md
  - Map Integration: ad_rss_map_integration/ad_rss_map_integration_python.md
- Doxygen:
  - Core Library: 'https://intel.github.io/ad-rss-lib/doxygen/ad_rss/index.html'
  - Map Integration: 'https://intel.github.io/ad-rss-lib/doxygen/ad_rss_map_integration/index.html'
- Code Coverage:
  - Core Library: 'https://intel.github.io/ad-rss-lib/coverage/ad_rss/'
  - Map Integration: 'https://intel.github.io/ad-rss-lib/coverage/ad_rss_map_integration/'
- FAQ: FAQ.md
- Changelog: CHANGELOG.md

#extra_css: [extra.css]

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: '.'
  - toc:
      permalink: true
      toc_depth: 2-3
  - pymdownx.emoji
  - pymdownx.arithmatex
  - mdx_truly_sane_lists
